### ISSUE TITLE
Unable to add offline source in offline mode

### ISSUE THREAD

**Issue by Vignesh-R16** [chaitu-ycr/py_canoe#13]
I have set the CANoe config to offline mode via python, but unable to add an offline source file to start the config using python

**Comment by chaitu-ycr** [comment]
setting offline source file feature not yet available in py_canoe package.
will be added in future.

**Comment by chaitu-ycr** [comment]
this feature implemented in latest version.
please upgrade package to 2.0.3 version.
pip install py_canoe --upgrade
https://pypi.org/project/py_canoe/2.0.3/
help document --> https://chaitu-ycr.github.io/py_canoe/999_reference/#src.py_canoe.CANoe.add_offline_source_log_file
