### ISSUE TITLE
Dispatch CANoe without opening a configuration

### ISSUE THREAD

**Issue by gfabiano** [chaitu-ycr/py_canoe#16]
On my environment sometime I restart the Python script but I dont want py_canoe reload everything.
It can be useful to make a dispatch method that not load a configuration in my opinion.

For now I modified the open method removing commenting this line for my configuration and works as expected.

` 166.           # self.__canoe_objects['Application'].Open(canoe_cfg, auto_save, prompt_user)`

**Comment by chaitu-ycr** [comment]
hi @gfabiano 

practically i won't recommend this approach since this has side effects when running test modules.
for basic methods this should be fine.

please create a pull request with implementation code.
