### ISSUE TITLE
Cannot open canoe cfg

### ISSUE THREAD

**Issue by varaprasanth** [chaitu-ycr/py_canoe#17]
Hi ,

i am facing issue with Canoe cfg .when i run the script, its showing below error , i have updated py_canoe also
![image](https://github.com/chaitu-ycr/py_canoe/assets/142930186/ef860235-3e89-411d-a378-19a663ff3443)

**Comment by chaitu-ycr** [comment]
Please update the package to the latest.
also make sure your CANoe version is >= 11 and python version >= 3.9
opening canoe configuration working for all users if above prerequisites are met.
Let me know if you are still facing issues even after following the steps mentioned.
