### ISSUE TITLE
Add method for calling/loading CAPL functions

### ISSUE THREAD

**Issue by Nyral** [chaitu-ycr/py_canoe#19]
Hello, having this feature would be really useful in my setup. Unfortunently, I couldn't figure out how to add it to your code.

Here's a working example: https://stackoverflow.com/a/37068335

Thank you.

**Comment by chaitu-ycr** [comment]
your requested feature implemented.
upgrade py_canoe to get latest features --> pip install py_canoe --upgrade
check this documentation for more info --> https://chaitu-ycr.github.io/py_canoe/999_reference/#src.py_canoe.CANoe.call_capl_function
