### ISSUE TITLE
Issue with canoe_inst = CANoe()

### ISSUE THREAD

**Issue by Iminthehouse** [chaitu-ycr/py_canoe#2]
I am having some issues running the code:
![image](https://user-images.githubusercontent.com/57605174/219893240-30043444-f7c2-446e-829b-fec02a471a1b.png)

**Comment by chaitu-ycr** [comment]
hey thanks for pointing this issue.
now this issue is fixed. now you have the option to provide py_canoe log directory. but be careful if you are not giving any path then default path will be 'D:\.py_canoe'

example:
canoe_inst = CANoe(**py_canoe_log_dir=r'D:\.py_canoe'**)
