### ISSUE TITLE
Call capl function does not work

### ISSUE THREAD

**Issue by Nyral** [chaitu-ycr/py_canoe#24]
Hello,

Thank you for taking an interest in implementing this, but unfortunately it doesn't work.

When calling function it returns KeyError, it cannot find the function in `self.meas.user_capl_function_obj_dict`.

I have passed the function name as argument during CANoe instance creation.

I'm using CANoe v15 with py_canoe v2.0.1 release.

**Comment by chaitu-ycr** [comment]
this issue resolved in latest version.
please upgrade package to 2.0.2 version.
pip install py_canoe --upgrade
https://pypi.org/project/py_canoe/2.0.2/

**Comment by Nyral** [comment]
it works now
