### ISSUE TITLE
Systen variable handle enhacements

### ISSUE THREAD

**Issue by Nyral** [chaitu-ycr/py_canoe#28]
Hello, I've found a few more use cases which aren't covered:

* A method to set/get variables of type array (Integer Array, Double Array, Data) is missing
Note: Some elements in Data Array are inverted, so you need to apply `hex(value&0xFF)` on them.
Also, make an option to only set part of an array (so add an optional argument for start position).
* System defined variables cannot be read (getting them works a bit different compared to User defined variables, the namespaces are nested in the same object)

![image](https://github.com/chaitu-ycr/py_canoe/assets/39315668/3e61afeb-b6fb-43af-987b-30a851035493)

**Comment by chaitu-ycr** [comment]
hi @Nyral 

i am able to read system defined system variable value mentioned in image.
```python
canoe_inst.get_system_variable_value("_Statistics::CAN1::Bursts")
```

if you are using any old package please upgrade to latest version.
```bat
pip install py_canoe --upgrade
```
latest available GitHub release tag --> https://github.com/chaitu-ycr/py_canoe/releases/tag/v2.1.0
for get/set any type of system variable is possible now. please check this usage example for reference
https://chaitu-ycr.github.io/py_canoe/004_usage/#getset-system-variable-or-define-system-variable
