### ISSUE TITLE
(-2147352567, '发生意外。', (0, 'Measurement::Start', 'User interface is busy', 'D:\\Softwares\\canoe\\Help01\\CANoeCANalyzer.chm', 4470, -2147418113), None)

### ISSUE THREAD

**Issue by tohsaka888** [chaitu-ycr/py_canoe#29]
When i use the method `start_measure`, sometimes i got this error.

```
(-2147352567, '发生意外。', (0, 'Measurement::Start', 'User interface is busy', 'D:\\Softwares\\canoe\\Help01\\CANoeCANalyzer.chm', 4470, -2147418113), None)
```

This is only an occasional occurrence, and most of the time it works. But I don't know why this happens.

Could you help me analyze the cause of this problem? Thank you very much!!!

**Comment by raghavinti** [comment]
You may see this error if the measurement is already running on the background. Make sure to stop the measurement if you have start measurement() in your python code.

**Comment by tohsaka888** [comment]
> You may see this error if the measurement is already running on the background. Make sure to stop the measurement if you have start measurement() in your python code.

Thank you for your help, but I don't think it is caused by this. I also had it before because when the simulation was running, I started measure. I remember that the error displayed was that the port cannot be accessed instead of `user interface busy`.

**Comment by chaitu-ycr** [comment]
hi @tohsaka888 
next time when you are facing this error can you please post screenshot of it.
also please register CANoe to a particular version if you have multiple CANoe softwares installed in your PC.
for example, if you want to register CANoe version 11 --> C:\Program Files\Vector CANoe 11.0\Exec64\RegisterComponents.exe

**Comment by tohsaka888** [comment]
> hi @tohsaka888 next time when you are facing this error can you please post screenshot of it. also please register CANoe to a particular version if you have multiple CANoe softwares installed in your PC. for example, if you want to register CANoe version 11 --> C:\Program Files\Vector CANoe 11.0\Exec64\RegisterComponents.exe

Dear @chaitu-ycr 

Thanks for your reply.I am using `Canoe 12.0` now.To be more precise, the version is  `Canoe 12.0 SP1`.

When the program faces this error, it will show a waring  dialog in the `user interface`.

![b1c02d844e082929ec078466b5a5909b](https://github.com/chaitu-ycr/py_canoe/assets/58759688/0bc01a04-26f3-450c-8471-45287dc3387a)

The content of the dialog is  `This operation cannot be completed because another program is running. Select "Switch to" to activate the running program and correct the problem.`.

I was puzzled by this phenomenon because it was only episodic and I couldn't understand what operation caused it to appear.

Looking forward to your reply!Thanks!!!

**Comment by tohsaka888** [comment]
The full log is:

```
error: (-2147352567, '�������⡣', (0, 'Measurement::Start', 'User interface is busy', 'D:\\Softwares\\canoe\\Help01\\CANoeCANalyzer.chm', 4470, -2147418113), None)
23:33:28 (-2147352567, '�������⡣', (0, 'Measurement::Start', 'User interface is busy', 'D:\\Softwares\\canoe\\Help01\\CANoeCANalyzer.chm', 4470, -2147418113), None)
23:33:28 2023-10-22 23:32:52,107 [CANOE_LOG] [INFO ]  CANoe Measurement Already Stopped. Measurement running status = False
23:33:28 [23:32:52.107]
23:33:28 Traceback (most recent call last):
23:33:28   File "D:\Jenkins\workspace\Tesla_auto_Test\tool\Automatic_stress_test\Tesla\TS_manager.py", line 42, in <module>
23:33:28     io_control.set_kl15(isOpen=True)  # 15�ϵ�
23:33:28     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:33:28   File "D:\Jenkins\workspace\Tesla_auto_Test\tool\Automatic_stress_test\Tesla\IOControl.py", line 22, in set_kl15
23:33:28     self.canoe_runner.start_measurement()
23:33:28   File "D:\Jenkins\workspace\Tesla_auto_Test\tool\Automatic_stress_test\Tesla\CanoeRunner.py", line 70, in start_measurement
23:33:28     self.canoe.start_measurement()
23:33:28   File "C:\Users\esw\AppData\Local\Programs\Python\Python311\Lib\site-packages\py_canoe.py", line 273, in start_measurement
23:33:28     self.__canoe_objects['Measurement'].Start()
23:33:28   File "C:\Users\esw\AppData\Local\Temp\2\gen_py\3.11\7F31DEB0-5BCC-11D3-8562-00105A3E017Bx0x1x59.py", line 9631, in Start
23:33:29     return self._oleobj_.InvokeTypes(3, LCID, 1, (24, 0), (),)
23:33:29            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:33:29 pywintypes.com_error: (-2147352567, '�������⡣', (0, 'Measurement::Start', 'User interface is busy', 'D:\\Softwares\\canoe\\Help01\\CANoeCANalyzer.chm', 4470, -2147418113), None)
23:33:29 
23:33:29 During handling of the above exception, another exception occurred:
23:33:29 
23:33:29 Traceback (most recent call last):
23:33:29   File "D:\Jenkins\workspace\Tesla_auto_Test\tool\Automatic_stress_test\Tesla\TS_manager.py", line 103, in <module>
23:33:29     asyncio.run(logger.write_error(str(error)))
23:33:29   File "C:\Users\esw\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
23:33:29     return runner.run(main)
23:33:29            ^^^^^^^^^^^^^^^^
23:33:29   File "C:\Users\esw\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 89, in run
23:33:29     raise ValueError("a coroutine was expected, got {!r}".format(coro))
23:33:29 ValueError: a coroutine was expected, got None
```

**Comment by chaitu-ycr** [comment]
> The full log is:
> 
> ```
> error: (-2147352567, '�������⡣', (0, 'Measurement::Start', 'User interface is busy', 'D:\\Softwares\\canoe\\Help01\\CANoeCANalyzer.chm', 4470, -2147418113), None)
> 23:33:28 (-2147352567, '�������⡣', (0, 'Measurement::Start', 'User interface is busy', 'D:\\Softwares\\canoe\\Help01\\CANoeCANalyzer.chm', 4470, -2147418113), None)
> 23:33:28 2023-10-22 23:32:52,107 [CANOE_LOG] [INFO ]  CANoe Measurement Already Stopped. Measurement running status = False
> 23:33:28 [23:32:52.107]
> 23:33:28 Traceback (most recent call last):
> 23:33:28   File "D:\Jenkins\workspace\Tesla_auto_Test\tool\Automatic_stress_test\Tesla\TS_manager.py", line 42, in <module>
> 23:33:28     io_control.set_kl15(isOpen=True)  # 15�ϵ�
> 23:33:28     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 23:33:28   File "D:\Jenkins\workspace\Tesla_auto_Test\tool\Automatic_stress_test\Tesla\IOControl.py", line 22, in set_kl15
> 23:33:28     self.canoe_runner.start_measurement()
> 23:33:28   File "D:\Jenkins\workspace\Tesla_auto_Test\tool\Automatic_stress_test\Tesla\CanoeRunner.py", line 70, in start_measurement
> 23:33:28     self.canoe.start_measurement()
> 23:33:28   File "C:\Users\esw\AppData\Local\Programs\Python\Python311\Lib\site-packages\py_canoe.py", line 273, in start_measurement
> 23:33:28     self.__canoe_objects['Measurement'].Start()
> 23:33:28   File "C:\Users\esw\AppData\Local\Temp\2\gen_py\3.11\7F31DEB0-5BCC-11D3-8562-00105A3E017Bx0x1x59.py", line 9631, in Start
> 23:33:29     return self._oleobj_.InvokeTypes(3, LCID, 1, (24, 0), (),)
> 23:33:29            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 23:33:29 pywintypes.com_error: (-2147352567, '�������⡣', (0, 'Measurement::Start', 'User interface is busy', 'D:\\Softwares\\canoe\\Help01\\CANoeCANalyzer.chm', 4470, -2147418113), None)
> 23:33:29 
> 23:33:29 During handling of the above exception, another exception occurred:
> 23:33:29 
> 23:33:29 Traceback (most recent call last):
> 23:33:29   File "D:\Jenkins\workspace\Tesla_auto_Test\tool\Automatic_stress_test\Tesla\TS_manager.py", line 103, in <module>
> 23:33:29     asyncio.run(logger.write_error(str(error)))
> 23:33:29   File "C:\Users\esw\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
> 23:33:29     return runner.run(main)
> 23:33:29            ^^^^^^^^^^^^^^^^
> 23:33:29   File "C:\Users\esw\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 89, in run
> 23:33:29     raise ValueError("a coroutine was expected, got {!r}".format(coro))
> 23:33:29 ValueError: a coroutine was expected, got None
> ```

hi @tohsaka888 
this error is due to another CANoe application running in backend. since COM port is already in use, new application instance wont be able to access same COM port.

this error occurs due to following reasons:
--> CANoe application not closed properly due to python script crash and it is still running in background.
--> same CANoe application opened with two different pc user names.

to avoid this issue make sure there is no canoe application running in background.
you can kill process using task manager or taskkill commandline tool.

thank you for reporting this issue. in future releases i will try to create a method to check and kill application before opening new instance.
for now temporarily please follow the sugessions provided.

**Comment by tohsaka888** [comment]
Thanks for your advice!

**Comment by chaitu-ycr** [comment]
hi @tohsaka888 

i updated and restructured lot of methods handling recently.
i believe this issue should be solved with latest updates. upgrade to latest package ```pip install py_canoe --upgrade```
comment back if you are still facing issue even after upgrading to latest version.
