### ISSUE TITLE
Issue when Canoe is already running

### ISSUE THREAD

**Issue by Abhiyong** [chaitu-ycr/py_canoe#3]

**Comment by Abhiyong** [comment]
Hello
First i run def startmeasurment() then Canoe started.
Then I comment out  #startmeasurment() and only run def TxRx()
When Canoe is running and i just try to send data then blow error occur.
![image](https://user-images.githubusercontent.com/126080089/220629602-3c1aab20-29c8-4478-a1ec-bfdcf896df30.png)

How to Tx/Rx data whith out again Start/Stop measurment?

**Comment by Abhiyong** [comment]
def open(self, canoe_cfg: str, visible=True, auto_save=False, prompt_user=False) -> None:
        if os.path.isfile(canoe_cfg):
            self.log.info(f'CANoe cfg "{canoe_cfg}" found.')
            self.__dispatch_canoe()
            self.__canoe_app_obj.Visible = visible
            **try:
                self.__canoe_app_obj.Open(canoe_cfg, auto_save, prompt_user)
            except:
                print ("Already open")**
            self.log.info(f'loaded CANoe config "{canoe_cfg}"')
            self.__fetch_canoe_cfg_general_data()
            self.log.info('Fetched CANoe System Variables.')
        else:
            self.log.info(f'CANoe cfg "{canoe_cfg}" not found.')

Updated code

**Comment by chaitu-ycr** [comment]
Win32com object will be created when CANoe is initialised.
Before exiting python code user should make sure CANoe application is stopped.
If user not stopping CANoe application then 2nd script cannot start CANoe application instance since CANoe is already running.
This is a known limitation right now.

So my recommendation is to execute both CANoe start stop in the same run.

**Comment by Abhiyong** [comment]
I have updated code, Now if Canoe is running then also works
def open(self, canoe_cfg: str, visible=True, auto_save=False, prompt_user=False) -> None:
        if os.path.isfile(canoe_cfg):
            #self.log.info(f'CANoe cfg "{canoe_cfg}" found.')
            self.__dispatch_canoe()
            self.__canoe_app_obj.Visible = visible
            #==========================================
            **try:
                self.__canoe_app_obj.Open(canoe_cfg, auto_save, prompt_user)
            except:
                print ("Canoe already open")**
            #===========================================
            #self.log.info(f'loaded CANoe config "{canoe_cfg}"')
            self.__fetch_canoe_cfg_general_data()
            #self.log.info('Fetched CANoe System Variables.')
        else:
            self.log.info(f'CANoe cfg "{canoe_cfg}" not found.')

**Comment by prashantlohar997** [comment]
> I have updated code, Now if Canoe is running then also works def open(self, canoe_cfg: str, visible=True, auto_save=False, prompt_user=False) -> None: if os.path.isfile(canoe_cfg): #self.log.info(f'CANoe cfg "{canoe_cfg}" found.') self.__dispatch_canoe() self.__canoe_app_obj.Visible = visible #========================================== **try: self.__canoe_app_obj.Open(canoe_cfg, auto_save, prompt_user) except: print ("Canoe is already Running")** #=========================================== #self.log.info(f'loaded CANoe config "{canoe_cfg}"') self.__fetch_canoe_cfg_general_data() #self.log.info('Fetched CANoe System Variables.') else: self.log.info(f'CANoe cfg "{canoe_cfg}" not found.')



> def open(self, canoe_cfg: str, visible=True, auto_save=False, prompt_user=False) -> None:
> if os.path.isfile(canoe_cfg):
> #self.log.info(f'CANoe cfg "{canoe_cfg}" found.')
> self.__dispatch_canoe()
> self.__canoe_app_obj.Visible = visible
> #==========================================
> **try: self.__canoe_app_obj.Open(canoe_cfg, auto_save, prompt_user) except: print ("Canoe is already Running")**
> #===========================================
> #self.log.info(f'loaded CANoe config "{canoe_cfg}"')
> self.__fetch_canoe_cfg_general_data()
> #self.log.info('Fetched CANoe System Variables.')
> else:

could you take a look and suggest me how you have resolved this issue.
I am also facing similar issue. 
https://github.com/chaitu-ycr/py_canoe/issues/8

**Comment by Alexrai123** [comment]
> I have updated code, Now if Canoe is running then also works def open(self, canoe_cfg: str, visible=True, auto_save=False, prompt_user=False) -> None: if os.path.isfile(canoe_cfg): #self.log.info(f'CANoe cfg "{canoe_cfg}" found.') self.__dispatch_canoe() self.__canoe_app_obj.Visible = visible #========================================== **try: self.__canoe_app_obj.Open(canoe_cfg, auto_save, prompt_user) except: print ("Canoe is already Running")** #=========================================== #self.log.info(f'loaded CANoe config "{canoe_cfg}"') self.__fetch_canoe_cfg_general_data() #self.log.info('Fetched CANoe System Variables.') else: self.log.info(f'CANoe cfg "{canoe_cfg}" not found.')

Where did u put this code ? I'm also having trouble to open 2 CANoe files at the same time
