### ISSUE TITLE
Library.IReplayBlock instance has no attribute Name

### ISSUE THREAD

**Issue by J0hn-Lawrence** [chaitu-ycr/py_canoe#38]
**Describe the bug**
Attribute 'Name' does not seem to exist for the instance of type Library.IReplayBlock. This prevents setting a replay block file with the set_replay_block_file() function.

**To Reproduce**
I tried to run the exact example code, that is in the docstring. Of course I provided valid paths to .cfg file and valid info for the replayblock.

```

>>> # The following example sets replay block file
            >>> canoe_inst = CANoe()
            >>> canoe_inst.open(r'D:\_kms_local\vector_canoe\py_canoe\demo_cfg\demo.cfg')
            >>> canoe_inst.set_replay_block_file(block_name='replay block name', recording_file_path='replay file including path')
            >>> canoe_inst.start_measurement()

```
The following error will appear when executing:
```
[CANOE_LOG] [INFO] failed to fetch replay blocks. '<win32com.gen_py.CANoe 16.4 Type Library.IReplayBlock instance at 0x12345>' object had no attribute 'Name'
```

**Expected behavior**
I expected no error message and that the provided replay log file would be set successfully.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Vector CANoe (please complete the following information):**
 - Version 16.4.4
 - Service Pack SP4

**Additional context**
Please let me know if anyone can reproduce this bug. If so maybe we can find a solution to fix the problem.

**Comment by J0hn-Lawrence** [comment]
Hey everyone

I found a temporary workaround:

If you add the following code to py_canoe.py setting the replay block file works flawlessly for me.

Additional import:
```
from win32com.client import CastTo 
````

Inside the function __fetch_replay_blocks() change the line 965 to these two lines:
```
casted_block = CastTo(replay_block, "IReplayBlock3")
replay_blocks[casted_block.Name] = casted_block

```

This fix has resolved the issue for me. I am not creating a pull request for this as of now as it requires an additional import and I want to discuss the solution first. 

Happy to exchange on this topic.

**Comment by chaitu-ycr** [comment]
hi @J0hn-Lawrence 

thank you for the finding. this issue is resolved now and updated source code.
please check out this GitHub release tag https://github.com/chaitu-ycr/py_canoe/releases/tag/v2.0.5
officially not yet release in PyPi.
from my side i checked with this [test_case](https://github.com/chaitu-ycr/py_canoe/blob/v2.0.5/tests/test_canoe.py#L161-L172)
can you please check and confirm whether this release fixes your issue.

**Comment by J0hn-Lawrence** [comment]
Hey @chaitu-ycr 

I just tested with the new release 2.0.5 and the issue I described above is resolved! 

Thank you for the work you do and the effort you put in this project. You are very much appreciated! 🫶
