### ISSUE TITLE
How to get the created system variables struct definition data

### ISSUE THREAD

**Issue by BertXin** [chaitu-ycr/py_canoe#45]

**Comment by chaitu-ycr** [comment]
i will notify here after implementation. if you have implementation code already please fork and create PR.

**Comment by chaitu-ycr** [comment]
hi @BertXin 

reading complete struct definition is not available.
but you can get symbolic value as return value for system variable
sample code 👉 https://github.com/chaitu-ycr/py_canoe/blob/main/tests/test_py_canoe.py#L145-L146
