### ISSUE TITLE
Have an Idea

### ISSUE THREAD

**Issue by Rajadeepanm** [chaitu-ycr/py_canoe#5]
Hello Chaitu,

This is Rajadeepan, a devops engineer.

This py_canoe project is very useful for the people like me who are new to CANoe Panels.

I have some configuration which has some test environments which i would like to execute all the test cases one by one. So I have written a code which might be useful if we integrate with this project.

So I would like to contribute to this project to parse test environments and execute all test modules in the CANoe test environment configuration.

I don't have any documentation updated for this. But I have followed some of your standards which you can modify later. 

Regards,
Rajadeepan

**Comment by chaitu-ycr** [comment]
Sure please Create pull request. I can merge your code after review.

**Comment by Rajadeepanm** [comment]
Great !!! Thank you.

I guess, I do not have enough permission to create a branch. So, Could you please provide access to create a new branch, commit and create pull request?

**Comment by chaitu-ycr** [comment]
Invited as collaborator
