### ISSUE TITLE
[BUG] Opening a configuration that is already open.

### ISSUE THREAD

**Issue by BjorniFPV** [chaitu-ycr/py_canoe#69]
In Version 2.1.3 it was possible to have CANoe open with a configuration loaded and then open the canoe_inst with that configuration. The configuration got reloaded and everything was fine. Doing this in Version 3.0 gives following Error:
 Error opening CANoe configuration: (-2147352567, 'Exception error occurred.', (0, None, None, None, 0, -2147467259), None)

I found it very convenient to have CANoe already open. 

1. Start CANoe
2. Open the CANoe configuration you want to use with py_canoe
3. Open canoe_inst with open function in py_canoe 
5. See error

Canoe_inst is successful opened

 - py_canoe version 3.0.0

 - OS: Windows 11
 - OS Version 23H2 (Build 22631.4460)
 - Vector CANoe Version 16
 - Vector CANoe Service Pack 6

**Comment by chaitu-ycr** [comment]
hi @BjorniFPV 

i created a new release with default open config options (auto_save=True, auto_stop=True).
py_canoe 3.0.1

let me know if it works for you.

if you are still facing same issue, please share the debug log messages above the error. this helps me in identifying which line creating issue.

**Comment by BjorniFPV** [comment]
Yes now it works for me.  Also with auto_save=False.

Thanks
