### ISSUE TITLE
Communicating Flask app with py_canoe module, through send_diag_request method getting ECU respond only 1st time. 

### ISSUE THREAD

**Issue by prashantlohar997** [chaitu-ycr/py_canoe#8]
This error occurs when object of canoe using as local in Flask app.
Diag ECU qualifier (ECU_NAME) not available in loaded CANoe config.

If I am passing canoe object outside of the any route in Flask app, It shows pywin32 related error.
File: <COMObject <unknown>>", line 2 in CreateRequestFromStream.
like: pywintypes.com_error (-21473221008, "CoInitialize has not been called, None, None")

2nd time while changing the parameter through flask frontend, I got these 2 above error.
I don't want to start and stop canoe measurement for every single request.

**Comment by chaitu-ycr** [comment]
hi @prashantlohar997
can please confirm whether this issue still present with latest py_canoe package
